version: '2'

services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    environment:
      NGINX_HOST: ${NGINX_HOST}
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - ./ms:/var/www
      - ./static:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
    networks:
      front:
      backend:


  web1:
    build:
      context: ms/web
      dockerfile: Dockerfile
    working_dir: /app
    container_name: web1
    environment:
      MSG: server 1
    networks:
      backend:
  web2:
    build:
      context: ms/web
      dockerfile: Dockerfile
    working_dir: /app
    container_name: web2
    environment:
      MSG: server 2
    networks:
      backend:
networks:
  backend:
  front:
